[package]
name = "cribro-desktop"
version = "0.1.0"
description = "CRIBRO ENGLISH — aplikacja desktopowa"
authors = ["Maciej Wyrozumski"]
edition = "2021"
rust-version = "1.77"

[lib]
name = "cribro_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-shell = "2"

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
panic = "abort"
strip = true
